# Copyright 2017-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=6

CRATES="
advapi32-sys-0.2.0
aho-corasick-0.5.3
aho-corasick-0.6.3
ansi_term-0.9.0
atty-0.2.2
bitflags-0.5.0
bitflags-0.8.2
cargo-script-0.2.7
chan-0.1.19
clap-2.23.2
either-1.1.0
env_logger-0.4.2
gcc-0.3.45
hoedown-6.0.0
itertools-0.4.19
itertools-0.5.10
kernel32-sys-0.2.2
ktmw32-sys-0.1.0
lazy_static-0.1.16
lazy_static-0.2.6
libc-0.2.21
log-0.3.7
memchr-0.1.11
memchr-1.0.1
ole32-sys-0.2.0
open-1.2.0
rand-0.3.15
redox_syscall-0.1.17
regex-0.1.80
regex-0.2.1
regex-syntax-0.3.9
regex-syntax-0.4.0
rustc-serialize-0.3.23
rustc_version-0.1.7
scan-rules-0.2.0
semver-0.1.20
semver-0.5.1
semver-parser-0.6.2
shaman-0.1.0
shell32-sys-0.1.1
strcursor-0.2.5
strsim-0.6.0
tempdir-0.3.5
term_size-0.3.0
thread-id-2.0.0
thread-id-3.0.0
thread_local-0.2.7
thread_local-0.3.3
time-0.1.36
toml-0.2.1
unicode-segmentation-0.1.2
unicode-segmentation-1.1.0
unicode-width-0.1.4
unreachable-0.1.1
utf8-ranges-0.1.3
utf8-ranges-1.0.0
uuid-sys-0.1.2
vec_map-0.7.0
void-1.0.2
winapi-0.2.8
winapi-build-0.1.1
winreg-0.4.0
"

inherit cargo

DESCRIPTION="A Cargo subcommand to run Rust scripts"
HOMEPAGE="https://github.com/DanielKeep/cargo-script"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="Apache-2.0" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
